---
Name: silverstripe-flow-config
---

SwipeStripe\Order\Order:
  extensions:
    - Isobar\Flow\Extensions\OrderExtension

SilverStripe\Omnipay\Service\PurchaseService:
  extensions:
    - Isobar\Flow\Extensions\PurchaseServiceExtension
